# Generated by Django 5.1.5 on 2025-06-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='usre',
            new_name='user',
        ),
    ]
