# Generated by Django 5.1.5 on 2025-07-02 16:48

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_statuse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='statuse',
            new_name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='last_update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
